# Generated by Django 2.1.3 on 2018-12-17 14:11

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownerinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=50, unique=True, verbose_name='电话')),
                ('identity_number', models.CharField(max_length=50, unique=True, verbose_name='身份证号码')),
                ('owner_name', models.CharField(default='www', max_length=50, verbose_name='船主姓名')),
            ],
            options={
                'verbose_name': '船主信息',
                'verbose_name_plural': '船主信息',
            },
        ),
        migrations.CreateModel(
            name='Shipinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jindu', models.FloatField(max_length=50, verbose_name='经度')),
                ('weidu', models.FloatField(max_length=50, verbose_name='纬度')),
                ('speed', models.FloatField(default=60, max_length=50, verbose_name='速度')),
                ('Freight_type', models.CharField(default='危险品', max_length=50, verbose_name='货运类型')),
                ('ship_status', models.CharField(default='航行中', max_length=50, verbose_name='船舶状态')),
                ('task_status', models.CharField(default='已完成', max_length=50, verbose_name='任务状态')),
                ('tonnage', models.FloatField(default=35, max_length=50, verbose_name='船舶吨位')),
                ('shipname', models.CharField(default='abc', max_length=50, null=True, verbose_name='船名')),
                ('ownerinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myauth.Ownerinfo', verbose_name='船主')),
            ],
            options={
                'verbose_name': '船舶信息',
                'verbose_name_plural': '船舶信息',
            },
        ),
        migrations.CreateModel(
            name='TestPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '船舶信息',
                'verbose_name_plural': '船舶信息',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容'),
        ),
    ]
