# Generated by Django 2.1.3 on 2018-12-22 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_auto_20181217_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipLocus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jindu', models.FloatField(max_length=50, verbose_name='经度')),
                ('weidu', models.FloatField(max_length=50, verbose_name='纬度')),
                ('shipname', models.CharField(default='abc', max_length=50, null=True, verbose_name='船名')),
                ('ownerinfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myauth.Ownerinfo', verbose_name='船主')),
            ],
            options={
                'verbose_name': '船舶信息',
                'verbose_name_plural': '船舶信息',
            },
        ),
        migrations.AlterField(
            model_name='testpicture',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
